# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:7.6.0
# Add your kibana plugins setup here
#RUN kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-6.6.0-0/sentinl-v6.6.1.zip
# Example: RUN kibana-plugin install <name|url>
                          